Update infra test data

diff --git a/kubernetes/generatedManifests/test/infrastructure/argocd/1-manifest/apps_v1-deployment-argocd-argocd-argo-cd-server.yaml b/kubernetes/generatedManifests/test/infrastructure/argocd/1-manifest/apps_v1-deployment-argocd-argocd-argo-cd-server.yaml
--- a/kubernetes/generatedManifests/test/infrastructure/argocd/1-manifest/apps_v1-deployment-argocd-argocd-argo-cd-server.yaml
+++ b/kubernetes/generatedManifests/test/infrastructure/argocd/1-manifest/apps_v1-deployment-argocd-argocd-argo-cd-server.yaml
@@ -3,13 +3,13 @@ kind: Deployment
 metadata:
   annotations:
     kubectl.kubernetes.io/last-applied-configuration: |
-      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"labels":{"app.kubernetes.io/component":"server","app.kubernetes.io/instance":"argocd","app.kubernetes.io/managed-by":"pulumi","app.kubernetes.io/name":"argo-cd","helm.sh/chart":"argo-cd-3.1.16"},"name":"argocd-argo-cd-server","namespace":"argocd"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/component":"server","app.kubernetes.io/instance":"argocd","app.kubernetes.io/name":"argo-cd"}},"strategy":{"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app.kubernetes.io/component":"server","app.kubernetes.io/instance":"argocd","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"argo-cd","helm.sh/chart":"argo-cd-3.1.16"}},"spec":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchLabels":{"app.kubernetes.io/component":"server","app.kubernetes.io/instance":"argocd","app.kubernetes.io/name":"argo-cd"}},"namespaces":["argocd"],"topologyKey":"kubernetes.io/hostname"},"weight":1}]}},"containers":[{"args":["--staticassets","/opt/bitnami/argo-cd/app","--repo-server","argocd-argo-cd-repo-server:8081","--logformat","text","--loglevel","info","--redis","argocd-redis-master:6379","--insecure"],"command":["argocd-server"],"env":[{"name":"REDIS_PASSWORD","valueFrom":{"secretKeyRef":{"key":"redis-password","name":"argocd-redis"}}}],"image":"docker.io/bitnami/argo-cd:2.3.3-debian-10-r25","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":8080},"initialDelaySeconds":10,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"name":"argocd-server","ports":[{"containerPort":8080,"name":"http","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":8080},"initialDelaySeconds":10,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{"limits":{},"requests":{}},"securityContext":{"runAsNonRoot":true,"runAsUser":1001},"volumeMounts":[{"mountPath":"/app/config/ssh","name":"ssh-known-hosts"},{"mountPath":"/app/config/server/tls","name":"argocd-repo-server-tls"}]}],"initContainers":[{"args":["-ec","#!/bin/bash\n\nset -o errexit\nset -o nounset\nset -o pipefail\n\n. /opt/bitnami/scripts/libos.sh\n. /opt/bitnami/scripts/liblog.sh\n\ncheck_redis_connection() {\n  local result=\"$(redis-cli -h argocd-redis-master -p 6379 PING)\"\n  if [[ \"$result\" != \"PONG\" ]]; then\n    false\n  fi\n}\n\ninfo \"Checking redis connection...\"\nif ! retry_while \"check_redis_connection\"; then\n    error \"Could not connect to the Redis server\"\n    return 1\nelse\n    info \"Connected to the Redis instance\"\nfi\n"],"command":["/bin/bash"],"env":[{"name":"REDISCLI_AUTH","valueFrom":{"secretKeyRef":{"key":"redis-password","name":"argocd-redis"}}}],"image":"docker.io/bitnami/redis:6.2.7-debian-10-r2","imagePullPolicy":"IfNotPresent","name":"wait-for-redis"}],"securityContext":{"fsGroup":1001},"serviceAccountName":"argocd-argo-cd-argocd-server","volumes":[{"configMap":{"name":"argocd-ssh-known-hosts-cm"},"name":"ssh-known-hosts"},{"name":"argocd-repo-server-tls","secret":{"items":[{"key":"tls.crt","path":"tls.crt"},{"key":"tls.key","path":"tls.key"},{"key":"ca.crt","path":"ca.crt"}],"optional":true,"secretName":"argocd-repo-server-tls"}}]}}}}
+      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"labels":{"app.kubernetes.io/component":"server","app.kubernetes.io/instance":"argocd","app.kubernetes.io/managed-by":"pulumi","app.kubernetes.io/name":"argo-cd","helm.sh/chart":"argo-cd-4.2.3"},"name":"argocd-argo-cd-server","namespace":"argocd"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/component":"server","app.kubernetes.io/instance":"argocd","app.kubernetes.io/name":"argo-cd"}},"strategy":{"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app.kubernetes.io/component":"server","app.kubernetes.io/instance":"argocd","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"argo-cd","helm.sh/chart":"argo-cd-4.2.3"}},"spec":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchLabels":{"app.kubernetes.io/component":"server","app.kubernetes.io/instance":"argocd","app.kubernetes.io/name":"argo-cd"}},"namespaces":["argocd"],"topologyKey":"kubernetes.io/hostname"},"weight":1}]}},"containers":[{"args":["argocd-server","--staticassets","/opt/bitnami/argo-cd/app","--repo-server","argocd-argo-cd-repo-server:8081","--logformat","text","--loglevel","info","--redis","argocd-redis-master:6379","--insecure"],"env":[{"name":"REDIS_PASSWORD","valueFrom":{"secretKeyRef":{"key":"redis-password","name":"argocd-redis"}}}],"image":"docker.io/bitnami/argo-cd:2.4.14-debian-11-r0","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":8080},"initialDelaySeconds":10,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"name":"argocd-server","ports":[{"containerPort":8080,"name":"http","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":8080},"initialDelaySeconds":10,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{"limits":{},"requests":{}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["all"]},"readOnlyRootFilesystem":false,"runAsNonRoot":true,"runAsUser":1001},"volumeMounts":[{"mountPath":"/app/config/ssh","name":"ssh-known-hosts"},{"mountPath":"/app/config/server/tls","name":"argocd-repo-server-tls"}]}],"initContainers":[{"args":["-ec","#!/bin/bash\n\nset -o errexit\nset -o nounset\nset -o pipefail\n\n. /opt/bitnami/scripts/libos.sh\n. /opt/bitnami/scripts/liblog.sh\n\ncheck_redis_connection() {\n  local result=\"$(redis-cli -h argocd-redis-master -p 6379  PING)\"\n  if [[ \"$result\" != \"PONG\" ]]; then\n    false\n  fi\n}\n\ninfo \"Checking redis connection...\"\nif ! retry_while \"check_redis_connection\"; then\n    error \"Could not connect to the Redis server\"\n    return 1\nelse\n    info \"Connected to the Redis instance\"\nfi\n"],"command":["/bin/bash"],"env":[{"name":"REDISCLI_AUTH","valueFrom":{"secretKeyRef":{"key":"redis-password","name":"argocd-redis"}}}],"image":"docker.io/bitnami/redis:7.0.5-debian-11-r5","imagePullPolicy":"IfNotPresent","name":"wait-for-redis"}],"securityContext":{"fsGroup":1001},"serviceAccountName":"argocd-argo-cd-argocd-server","volumes":[{"configMap":{"name":"argocd-ssh-known-hosts-cm"},"name":"ssh-known-hosts"},{"name":"argocd-repo-server-tls","secret":{"items":[{"key":"tls.crt","path":"tls.crt"},{"key":"tls.key","path":"tls.key"},{"key":"ca.crt","path":"ca.crt"}],"optional":true,"secretName":"argocd-repo-server-tls"}}]}}}}
   labels:
     app.kubernetes.io/component: server
     app.kubernetes.io/instance: argocd
     app.kubernetes.io/managed-by: pulumi
     app.kubernetes.io/name: argo-cd
-    helm.sh/chart: argo-cd-3.1.16
+    helm.sh/chart: argo-cd-4.2.3
   name: argocd-argo-cd-server
   namespace: argocd
 spec:
@@ -28,7 +28,7 @@ spec:
         app.kubernetes.io/instance: argocd
         app.kubernetes.io/managed-by: Helm
         app.kubernetes.io/name: argo-cd
-        helm.sh/chart: argo-cd-3.1.16
+        helm.sh/chart: argo-cd-4.2.3
     spec:
       affinity:
         podAntiAffinity:
@@ -45,6 +45,7 @@ spec:
             weight: 1
       containers:
       - args:
+        - argocd-server
         - --staticassets
         - /opt/bitnami/argo-cd/app
         - --repo-server
@@ -56,15 +57,13 @@ spec:
         - --redis
         - argocd-redis-master:6379
         - --insecure
-        command:
-        - argocd-server
         env:
         - name: REDIS_PASSWORD
           valueFrom:
             secretKeyRef:
               key: redis-password
               name: argocd-redis
-        image: docker.io/bitnami/argo-cd:2.3.3-debian-10-r25
+        image: docker.io/bitnami/argo-cd:2.4.14-debian-11-r0
         imagePullPolicy: IfNotPresent
         livenessProbe:
           failureThreshold: 3
@@ -93,6 +92,11 @@ spec:
           limits: {}
           requests: {}
         securityContext:
+          allowPrivilegeEscalation: false
+          capabilities:
+            drop:
+            - all
+          readOnlyRootFilesystem: false
           runAsNonRoot: true
           runAsUser: 1001
         volumeMounts:
@@ -114,7 +118,7 @@ spec:
           . /opt/bitnami/scripts/liblog.sh
 
           check_redis_connection() {
-            local result="$(redis-cli -h argocd-redis-master -p 6379 PING)"
+            local result="$(redis-cli -h argocd-redis-master -p 6379  PING)"
             if [[ "$result" != "PONG" ]]; then
               false
             fi
@@ -135,7 +139,7 @@ spec:
             secretKeyRef:
               key: redis-password
               name: argocd-redis
-        image: docker.io/bitnami/redis:6.2.7-debian-10-r2
+        image: docker.io/bitnami/redis:7.0.5-debian-11-r5
         imagePullPolicy: IfNotPresent
         name: wait-for-redis
       securityContext:
