Run prettier

diff --git a/kubernetes/manifests/generated/development/infrastructure/argocd/1-manifest/deployment-argocd-argocd-argo-cd-server.yaml b/kubernetes/manifests/generated/development/infrastructure/argocd/1-manifest/deployment-argocd-argocd-argo-cd-server.yaml
--- a/kubernetes/manifests/generated/development/infrastructure/argocd/1-manifest/deployment-argocd-argocd-argo-cd-server.yaml
+++ b/kubernetes/manifests/generated/development/infrastructure/argocd/1-manifest/deployment-argocd-argocd-argo-cd-server.yaml
@@ -33,126 +33,126 @@ spec:
       affinity:
         podAntiAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:
-          - podAffinityTerm:
-              labelSelector:
-                matchLabels:
-                  app.kubernetes.io/component: server
-                  app.kubernetes.io/instance: argocd
-                  app.kubernetes.io/name: argo-cd
-              namespaces:
-              - argocd
-              topologyKey: kubernetes.io/hostname
-            weight: 1
+            - podAffinityTerm:
+                labelSelector:
+                  matchLabels:
+                    app.kubernetes.io/component: server
+                    app.kubernetes.io/instance: argocd
+                    app.kubernetes.io/name: argo-cd
+                namespaces:
+                  - argocd
+                topologyKey: kubernetes.io/hostname
+              weight: 1
       containers:
-      - args:
-        - --staticassets
-        - /opt/bitnami/argo-cd/app
-        - --repo-server
-        - argocd-argo-cd-repo-server:8081
-        - --logformat
-        - text
-        - --loglevel
-        - info
-        - --redis
-        - argocd-redis-master:6379
-        - --insecure
-        command:
-        - argocd-server
-        env:
-        - name: REDIS_PASSWORD
-          valueFrom:
-            secretKeyRef:
-              key: redis-password
-              name: argocd-redis
-        image: docker.io/bitnami/argo-cd:2.3.3-debian-10-r25
-        imagePullPolicy: IfNotPresent
-        livenessProbe:
-          failureThreshold: 3
-          httpGet:
-            path: /healthz
-            port: 8080
-          initialDelaySeconds: 10
-          periodSeconds: 10
-          successThreshold: 1
-          timeoutSeconds: 1
-        name: argocd-server
-        ports:
-        - containerPort: 8080
-          name: http
-          protocol: TCP
-        readinessProbe:
-          failureThreshold: 3
-          httpGet:
-            path: /healthz
-            port: 8080
-          initialDelaySeconds: 10
-          periodSeconds: 10
-          successThreshold: 1
-          timeoutSeconds: 1
-        resources:
-          limits: {}
-          requests: {}
-        securityContext:
-          runAsNonRoot: true
-          runAsUser: 1001
-        volumeMounts:
-        - mountPath: /app/config/ssh
-          name: ssh-known-hosts
-        - mountPath: /app/config/server/tls
-          name: argocd-repo-server-tls
+        - args:
+            - --staticassets
+            - /opt/bitnami/argo-cd/app
+            - --repo-server
+            - argocd-argo-cd-repo-server:8081
+            - --logformat
+            - text
+            - --loglevel
+            - info
+            - --redis
+            - argocd-redis-master:6379
+            - --insecure
+          command:
+            - argocd-server
+          env:
+            - name: REDIS_PASSWORD
+              valueFrom:
+                secretKeyRef:
+                  key: redis-password
+                  name: argocd-redis
+          image: docker.io/bitnami/argo-cd:2.3.3-debian-10-r25
+          imagePullPolicy: IfNotPresent
+          livenessProbe:
+            failureThreshold: 3
+            httpGet:
+              path: /healthz
+              port: 8080
+            initialDelaySeconds: 10
+            periodSeconds: 10
+            successThreshold: 1
+            timeoutSeconds: 1
+          name: argocd-server
+          ports:
+            - containerPort: 8080
+              name: http
+              protocol: TCP
+          readinessProbe:
+            failureThreshold: 3
+            httpGet:
+              path: /healthz
+              port: 8080
+            initialDelaySeconds: 10
+            periodSeconds: 10
+            successThreshold: 1
+            timeoutSeconds: 1
+          resources:
+            limits: {}
+            requests: {}
+          securityContext:
+            runAsNonRoot: true
+            runAsUser: 1001
+          volumeMounts:
+            - mountPath: /app/config/ssh
+              name: ssh-known-hosts
+            - mountPath: /app/config/server/tls
+              name: argocd-repo-server-tls
       initContainers:
-      - args:
-        - -ec
-        - |
-          #!/bin/bash
+        - args:
+            - -ec
+            - |
+              #!/bin/bash
 
-          set -o errexit
-          set -o nounset
-          set -o pipefail
+              set -o errexit
+              set -o nounset
+              set -o pipefail
 
-          . /opt/bitnami/scripts/libos.sh
-          . /opt/bitnami/scripts/liblog.sh
+              . /opt/bitnami/scripts/libos.sh
+              . /opt/bitnami/scripts/liblog.sh
 
-          check_redis_connection() {
-            local result="$(redis-cli -h argocd-redis-master -p 6379 PING)"
-            if [[ "$result" != "PONG" ]]; then
-              false
-            fi
-          }
+              check_redis_connection() {
+                local result="$(redis-cli -h argocd-redis-master -p 6379 PING)"
+                if [[ "$result" != "PONG" ]]; then
+                  false
+                fi
+              }
 
-          info "Checking redis connection..."
-          if ! retry_while "check_redis_connection"; then
-              error "Could not connect to the Redis server"
-              return 1
-          else
-              info "Connected to the Redis instance"
-          fi
-        command:
-        - /bin/bash
-        env:
-        - name: REDISCLI_AUTH
-          valueFrom:
-            secretKeyRef:
-              key: redis-password
-              name: argocd-redis
-        image: docker.io/bitnami/redis:6.2.7-debian-10-r2
-        imagePullPolicy: IfNotPresent
-        name: wait-for-redis
+              info "Checking redis connection..."
+              if ! retry_while "check_redis_connection"; then
+                  error "Could not connect to the Redis server"
+                  return 1
+              else
+                  info "Connected to the Redis instance"
+              fi
+          command:
+            - /bin/bash
+          env:
+            - name: REDISCLI_AUTH
+              valueFrom:
+                secretKeyRef:
+                  key: redis-password
+                  name: argocd-redis
+          image: docker.io/bitnami/redis:6.2.7-debian-10-r2
+          imagePullPolicy: IfNotPresent
+          name: wait-for-redis
       securityContext:
         fsGroup: 1001
       serviceAccountName: argocd-argo-cd-argocd-server
       volumes:
-      - configMap:
-          name: argocd-ssh-known-hosts-cm
-        name: ssh-known-hosts
-      - name: argocd-repo-server-tls
-        secret:
-          items:
-          - key: tls.crt
-            path: tls.crt
-          - key: tls.key
-            path: tls.key
-          - key: ca.crt
-            path: ca.crt
-          optional: true
-          secretName: argocd-repo-server-tls
+        - configMap:
+            name: argocd-ssh-known-hosts-cm
+          name: ssh-known-hosts
+        - name: argocd-repo-server-tls
+          secret:
+            items:
+              - key: tls.crt
+                path: tls.crt
+              - key: tls.key
+                path: tls.key
+              - key: ca.crt
+                path: ca.crt
+            optional: true
+            secretName: argocd-repo-server-tls
